import Navigation from "./components/navigation/navbar"
import { Inter  } from "next/font/google";
import "./globals.css";
import RouteData from "./types/route_data";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

const routes: RouteData[] = [
  {
    route: "/login",
    text: "Login"
  },
  {
    route: "/home",
    text: "Home"
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-lt-installed="true">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Navigation routes={routes} />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}