import Navigation from "./components/navigation/navbar"
import { Inter  } from "next/font/google";
import "./globals.css";
import RouteData from "./types/route_data";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

const routes: RouteData[] = [
  {
    route: "/login",
    text: "Login"
  },
  {
    route: "/home",
    text: "Home"
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <html lang="en">
    <MantineProvider theme={theme}>
      <body className={inter.className}>
        <Navigation routes={routes} />
          {children}
        </body>
      </MantineProvider>
    </html>
    </>
  );
}