services:

  db:
    image: postgres
    container_name: flimgo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_db
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready", "-h", "db" ]
#      interval: 5s
#      retries: 5
#      start_period: 20s

  pgadmin:
    container_name: flimgo_pgadmin
    image: dpage/pgadmin4
    depends_on:
      db:
        condition: service_started
    restart: always
    ports:
      - "8888:80"
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  back:
    container_name: flimgo_back
    build: ./back
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./back
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      db:
        condition: service_started
    restart: always

  front:
    container_name: flimgo_front
    build: ./front
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules/
    depends_on:
      back:
        condition: service_started

configs:
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Flimgo",
        "Host": "${POSTGRES_HOST}",
        "Port": ${POSTGRES_PORT},
        "MaintenanceDB": "postgres",
        "Username": "${POSTGRES_USER}",
        "SSLMode": "prefer"
      }}}