services:

  db:
    image: postgres
    container_name: flimgo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: my_db
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready", "-h", "db" ]
#      interval: 5s
#      retries: 5
#      start_period: 20s

  pgadmin:
    image: dpage/pgadmin4
    container_name: flimgo_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_started

  back:
    container_name: flimgo_back
    build: ./back
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: ./back
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      db:
        condition: service_started

  front:
    container_name: flimgo_front
    build: ./front
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./front
          target: /app
          ignore:
            - node_modules/
    depends_on:
      back:
        condition: service_started
